### PR TITLE
Throw error when host is not reachable

### LINKED ISSUE #35: client.connect() does not throw exception on no connection
When using client.connect() to connect to a Asterisk server (v 13.6.0), the client.connec() command does not throw an exception, emit any event nor do anything when it cannot connect to the server. This makes it impossible to detect if the client is actually connected or not

### PR DESCRIPTION
**Pull request by jp1987**
Fixes #35

### CODE REVIEW

**Comment by jp1987** [comment]
This is mostly based on #12, but that has been inactive for over 3 years now and we REALLY need this. I used pretty much the same logic, except for using a promise reject when catching the error, that seems to make the most sense to me. Would be great if we could get this merged.

**Comment by chadxz** [comment]
Just curious, is there any reason you're not bubbling up the request error as-is instead of wrapping it in another Error object?

**Comment by chadxz** [comment]
When swagger encounters an error it causes the library to emit an "APILoadError" event. Seems like it'd be good to keep that even if the host is not reachable.

**Comment by chadxz** [comment]
> is there any reason you're not bubbling up the request error as-is instead of wrapping it in another Error object?

^This still isn't clear to me. I haven't dug into the request implementation, but I wonder if assuming that the host is not reachable is the reason the error occurred is a correct assumption.

Also, since this changes the behavior of the

**Comment by jp1987** [comment]
Sorry, I'm not sure what you mean by "I wonder if assuming that the host is not reachable is the reason the error occurred is a correct assumption". Can you elaborate?

I upped the version to 1.2.0 and updated the changelog.

**Comment by chadxz** [comment]
In your code you are treating any error from request as if it is caused by the host being unreachable. I'm asking- is this the right thing to do? Are there other classes of problems that the user may want to know about that we are re-casting as a "host not reachable" error?

**Comment by jp1987** [comment]
Right, I see what you mean. I looked into the request lib and they appear to use the native http module, which has the following [error codes](https://nodejs.org/docs/latest/api/errors.html#errors_common_system_errors) ([exhaustive list](http://man7.org/linux/man-pages/man3/errno.3.html)).

To me it makes the most sense to watch for ETIMEDOUT, ENOTFOUND and ECONNREFUSED. So I am filtering for these now.

**Comment by jp1987** [comment]
ETIMEDOUT is a bit tricky to write a test case for [example here](https://stackoverflow.com/questions/36533807/how-to-etimedout-with-nock-and-request-library), which would require a bit of an overhaul of tests/helpers.js (it needs to return another client that simulates the timeout), so I've skipped that for now (basically all that it would test is the indexOf function, which the other 2 test cases now cover).

File: lib/client.js [hunk 1]
```diff
@@ -26,6 +27,9 @@ var backoff = require('backoff-func');
 var _resources = require('./resources.js');
 var _utils = require('./utils.js');
 
+var hostIsNotReachableErrorCodes =
+    ['ETIMEDOUT', 'ENOTFOUND', 'ECONNREFUSED'];
```
Comment (chadxz) [inline lib/client.js]: Please bring this variable declaration down directly above the if statement, or inline the array. This is purely for readability.

File: lib/client.js [hunk 2]
```diff
@@ -107,10 +111,19 @@ Client.prototype._attachApi = function () {
...
-      url: ariUrl,
-      success: swaggerLoaded,
-      failure: swaggerFailed
+    request(ariUrl, function (err) {
+        if (err && hostIsNotReachableErrorCodes.indexOf(err.code) !== -1) {
+            err.name = 'HostIsNotReachable';
+
+            self.emit('APILoadError', err);
+            reject(err);
+      } else {
```
Comment (chadxz) [inline lib/client.js]: indentation here needs to be fixed. It's mixing 2 and 4 spaces looks like.

File: test/client.js [hunk 3]
```diff
@@ -115,6 +115,11 @@ var operations = {
 describe('client', function () {
 
   var url = 'http://localhost:%s';
+  var hostIsNotReachableUrls =
+      {
+        ENOTFOUND: 'http://notthere:8088',
+        ECONNREFUSED: 'http://localhost:65535'
+      };
```
Comment (chadxz) [inline test/client.js]: you can use [nock#delayConnection](https://github.com/nock/nock#delay-the-connection) to test ETIMEDOUT

File: test/client.js [hunk 4]
```diff
@@ -148,6 +153,24 @@ describe('client', function () {
     client.connect(url, user, pass, done);
   });
 
+  it('should send an error on ENOTFOUND', function (done) {
+    client.connect(
+        hostIsNotReachableUrls.ENOTFOUND, user, pass, function (err) {
+      if (err && err.name === 'HostIsNotReachable') {
+        done();
+      }
+    });
```
Comment (chadxz) [inline test/client.js]: your tests need an assert.fail("message") for the else case so that if the test fails, you get a descriptive message quickly instead of an ambiguous test timeout.

File: test/client.js (hunk 3 above)
Comment (jp1987) [reply test/client.js]: Spent some time on trying to get that to work, however the hock API doesn't support this yet, see [here](https://github.com/mmalecki/hock/pull/34)

File: lib/client.js (hunk 2 above)
Comment (jp1987) [reply lib/client.js]: Done

File: lib/client.js (hunk 1 above)
Comment (jp1987) [reply lib/client.js]: Done

File: test/client.js (hunk 3 above)
Comment (chadxz) [reply test/client.js]: Why hock vs. nock?

Comment (chadxz) [reply test/client.js]: I see we already have that in this library. huh. ok.

**Comment by jp1987** [comment]
Can we get this merged then?

**Comment by chadxz** [comment]
Sam's gonna do it

**Comment by samuelg** [comment]
Tagged and published to NPM.

**Comment by chadxz** [comment]
@jp1987 thank you for your contribution!
